[simulation_params]
# note: list of values should be comma separated without spaces
n_sim = 30
sample_size = 1250
val_share = 0.2
snr = 5
datasets_yaml = ./configs/temp_datasets_xgb.yaml
models_yaml = ./configs/temp_models_xgb.yaml
var_decomp = [["XGBoost_OF", "XGBoost_OT"], [1250], ["SimpleNormalCorrelated", "Friedman1", "FeynmanI.29.16"]]

[simulation_metadata]
n_test = 10000
n_groundtruth_mc = 10000
k_cv = 5
groundtruth_mc_data_seed = 123456
n_mc_datasets = 30
mc_dataset_base_seed = 123456
n_tuning_trials = 200
n_tuning_val = 10000
tuning_data_seed = 999999
tuning_metric = neg_mean_squared_error
tuning_direction = maximize

[storage]
simulation_name = main_study_xgb
# <path-to-experiments-dir/experiments>
simulations_dir = /dss/dsshome1/07/ra42ziz2/research/paper_2026_xai_feature_effects_code/experiments
model_results = /results/model_results.db
effects_results = /results/effects_results.db
tuning_studies_folder = tuning
# <path-to-logs-dir/logs> 
log_dir = /dss/dsshome1/07/ra42ziz2/research/paper_2026_xai_feature_effects_code/logs

[feature_effects]
grid_points = 100
centered = 1
remove_first_last = 1
